name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Wait for Redis
        run: |
          ruby -rsocket -e 'deadline = Time.now + 30; loop do; begin; TCPSocket.new("127.0.0.1", 6379).close; break; rescue Errno::ECONNREFUSED; raise "Redis not reachable" if Time.now > deadline; sleep 1; end; end'
      - name: Run RSpec
        env:
          REDIS_URL: redis://127.0.0.1:6379/15
        run: bundle exec rspec --format documentation
      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/index.html
          if-no-files-found: ignore

  rubocop:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --display-only-fails --format progress

  version_check:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - rspec
      - rubocop
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Verify version bump
        run: |
          commit_count=$(git rev-list --count HEAD)
          if [ "$commit_count" -le 1 ]; then
            if git show HEAD:lib/sidekiq/forked/worker/version.rb >/dev/null 2>&1; then
              exit 0
            else
              echo 'Initial master commit must include lib/sidekiq/forked/worker/version.rb.'
              exit 1
            fi
          fi

          if ! git diff --name-only HEAD^ HEAD | grep -q '^lib/sidekiq/forked/worker/version.rb$'; then
            echo 'Version must be updated in lib/sidekiq/forked/worker/version.rb before merging to master.'
            exit 1
          fi

  build_gem:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - version_check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Build gem
        run: gem build sidekiq-forked-worker.gemspec
      - name: Upload gem artifact
        uses: actions/upload-artifact@v4
        with:
          name: sidekiq-forked-worker-gem
          path: sidekiq-forked-worker-*.gem
